### ISSUE TITLE
JSON in enricht has in publicname JRCNMxxxxx identifier

### ISSUE THREAD

**Issue by jmillanacosta** [h2020-sbd4nano/sbd-data-ambit#3]
Take these as specific materials, just like the ERMxxx identifiers in the name field

**Comment by vedina** [comment]
JRCNMxxx are intentionally in public name

**Comment by egonw** [comment]
Implemented:

![image](https://github.com/h2020-sbd4nano/sbd-data-ambit/assets/26721/f222be75-ea0e-40fc-afdf-767746d13666)

**Comment by egonw** [comment]
> JRCNMxxx are intentionally in public name

Just curious: why? Is it more visible than the 'name' field?
